// Fixtures for the staged scenes of Chapters 5 and 6 (docs/expressive/SCENES.md "Performed overworld"; the notes
// are docs/expressive/reports/staging_ch5_ch6.md). One entry per scene, in the same shape as
// tests/e2e/staging_ch12_cases.mjs: where it plays (map, where you stand and face), who travels with you, the flags,
// quests, items, words and scenes already seen (`seen`) that the moment needs, and the branches worth playing
// (choice picks in order, companions, flags, a challenge or activity that is not passed). Played by
// tests/e2e/staging_runner.mjs through tests/e2e/staging_chapters.mjs --ch=5 / --ch=6.
//   { ch, scene, map, at: [x, y, dir], comp, talk, flags, quests, items, words, vars, player, seen, fail,
//     variants: [{ name, picks, comp, comps, flags, items, quests, seen, at, fail, … }], comps, expect }
const ALL4 = ['nao', 'mio', 'ren', 'suzu'];
const F = (...objs) => Object.assign({}, ...objs);

// ---- Chapter 5: Lanternfall -------------------------------------------------------------------------------
const L0 = { rw_arrived: true, departed: true, ch1_done: true, ch2_done: true, ch3_done: true, ch4_done: true };
const LA = F(L0, { lf_arrived: true }); // on the Lantern Road
const LT = F(LA, { lf_town_intro: true }); // in town, before the bell
const LB = F(LT, { lf_ledger_seen: true, lf_akari_key: true, lf_yae_told: true, lf_tokuji_told: true, lf_tokuji_boat: true, lf_tower_entered: true, lf_gate_a: true, lf_gate_b: true, lf_gate_c: true, lf_koe: true, lf_boss_done: true, lf_bell_rung: true }); // after the bell
const LD = F(LB, { lf_after_town: true, ch5_done: true }); // the chapter done
const LW = F(LT, { lf_yae_told: true, lf_tokuji_told: true, lf_tokuji_boat: true, lf_tower_entered: true }); // in the bell tower
const LM = F(LW, { lf_up_closed: true, lf_gate_a: true, lf_mid_seen: true, lf_shortcut: true }); // the gate works
const LL = F(LM, { lf_gate_b: true, lf_low_seen: true }); // the drowned stair
const LP = F(LD, { sa_arrived: true, ch6_done: true, sa_done: true, post: true, postgame: true }); // after the ending
const CH5 = [
  // 20_town.js
  { ch: 5, scene: 'lf.arrive', map: 'lf.road', at: [2, 13, 'right'], flags: L0, comps: ALL4, minLines: 4, expect: { pc: ['lookroad', 'shadeeyes', 'point'] } },
  { ch: 5, scene: 'lf.road_bench', map: 'lf.road', at: [17, 14, 'down'], flags: LA, comps: ALL4, expect: { pc: ['lookroad'] } },
  { ch: 5, scene: 'lf.road_lantern', map: 'lf.road', at: [23, 11, 'up'], flags: LA, expect: { pc: ['observe'] },
    variants: [{ name: 'blank · ren', comp: 'ren', expect: { comp: ['observe'] } }, { name: 'blank · nao', comp: 'nao' }, { name: 'lit', comp: 'mio', flags: LD }] },
  { ch: 5, scene: 'lf.road_north_locked', map: 'lf.road', at: [24, 1, 'up'], flags: LA, variants: [{ name: 'at the left of the gap', comps: ALL4 }, { name: 'at the right', at: [25, 1, 'up'], comp: 'ren' }], expect: { pc: ['lookroad'] } },
  { ch: 5, scene: 'lf.town_intro', map: 'lf.town', at: [2, 17, 'right'], flags: LA, comps: ALL4, minLines: 12,
    expect: { lf_hayato: ['palm', 'present', 'stamp', 'handover', 'chin'], pc: ['observe', 'receive', 'point'] } },
  { ch: 5, scene: 'lf.board', map: 'lf.town', at: [26, 18, 'up'], flags: LT, expect: { pc: ['observe'] },
    variants: [{ name: 'before the bell', comps: ALL4, expect: { pc: ['lookbetween'] } }, { name: 'after the bell', comp: 'nao', flags: LB }] },
  { ch: 5, scene: 'lf.bench_canal', map: 'lf.town', at: [48, 32, 'down'], flags: LT, comps: ALL4, expect: { pc: ['cupear'] } },
  { ch: 5, scene: 'lf.nagi', map: 'lf.town', at: [13, 17, 'down'], talk: 'lf_nagi', flags: LT, expect: { lf_nagi: ['tendlamp'] },
    variants: [{ name: 'first · ren', comp: 'ren', expect: { lf_nagi: ['point', 'glance'], comp: ['chin'] } }, { name: 'first · mio', comp: 'mio' }, { name: 'again', comp: 'nao', seen: ['lf.nagi'] }] },
  { ch: 5, scene: 'lf.kei', map: 'lf.town', at: [17, 25, 'left'], talk: 'lf_kei', flags: LT, comps: ALL4, minLines: 5, expect: { lf_kei: ['peek', 'shake', 'shrug', 'point'] } },
  { ch: 5, scene: 'lf.shu', map: 'lf.gardens', at: [8, 18, 'down'], talk: 'lf_shu', flags: LT, variants: [{ name: 'mio', comp: 'mio', expect: { comp: ['observe'] } }, { name: 'ren', comp: 'ren' }], expect: { lf_shu: ['brow', 'size', 'lowered'], pc: ['palm'] } },
  { ch: 5, scene: 'lf.setsu', map: 'lf.inn', at: [2, 5, 'up'], talk: 'lf_setsu', flags: LT, comp: 'nao', variants: [{ name: 'rest', picks: [0], expect: { lf_setsu: ['palm', 'laugh'] } }, { name: 'all right', picks: [1] }], expect: { pc: ['lookroad'] } },
  { ch: 5, scene: 'lf.setsu_after', map: 'lf.inn', at: [2, 5, 'up'], talk: 'lf_setsu', flags: LB, comp: 'ren', variants: [{ name: 'rest', picks: [0] }, { name: 'another time', picks: [1] }], expect: { lf_setsu: ['celebrate', 'palm'] } },
  { ch: 5, scene: 'lf.setsu_post', map: 'lf.inn', at: [2, 5, 'up'], talk: 'lf_setsu', comp: 'suzu', flags: LP, picks: [1],
    variants: [{ name: 'Kasane tried', flags: F(LP, { end_kasane_trial: true }), expect: { lf_setsu: ['palm', 'lookroad'] } }, { name: 'Kasane the keeper', flags: F(LP, { end_kasane_keeper: true }), picks: [0] }] },
  { ch: 5, scene: 'lf.ritsu', map: 'lf.cafe', at: [2, 4, 'up'], talk: 'lf_ritsu', flags: LT,
    variants: [{ name: 'helped · suzu', comp: 'suzu', picks: [0], expect: { lf_ritsu: ['laugh', 'present'], comp: ['chin', 'check'] } }, { name: 'helped · mio', comp: 'mio', picks: [0] }, { name: 'another time', comp: 'nao', picks: [1] }, { name: 'orders muddled', comp: 'ren', picks: [0], fail: true }],
    expect: { lf_ritsu: ['fidget', 'palm'] } },
  { ch: 5, scene: 'lf.ritsu_after', map: 'lf.cafe', at: [2, 4, 'up'], talk: 'lf_ritsu', flags: LB, comp: 'mio', variants: [{ name: 'help', picks: [0] }, { name: 'another time', picks: [1] }], expect: { lf_ritsu: ['celebrate', 'palm'] } },
  { ch: 5, scene: 'lf.ritsu_post', map: 'lf.cafe', at: [2, 4, 'up'], talk: 'lf_ritsu', flags: LP, comp: 'ren', picks: [1], expect: { lf_ritsu: ['laugh'] } },
  { ch: 5, scene: 'lf.masaru', map: 'lf.bakery', at: [4, 4, 'up'], talk: 'lf_masaru', flags: LT, comps: ALL4, minLines: 6, expect: { lf_masaru: ['laugh', 'count', 'knead'], pc: ['observe'] } },
  { ch: 5, scene: 'lf.masaru_after', map: 'lf.bakery', at: [4, 4, 'up'], talk: 'lf_masaru', flags: LB, comp: 'suzu', expect: { lf_masaru: ['laugh', 'knead'] } },
  { ch: 5, scene: 'lf.masaru_post', map: 'lf.bakery', at: [4, 4, 'up'], talk: 'lf_masaru', comp: 'nao', flags: LP,
    variants: [{ name: 'Kasane tried', flags: F(LP, { end_kasane_trial: true }) }, { name: 'otherwise' }], expect: { lf_masaru: ['count', 'laugh'] } },
  { ch: 5, scene: 'lf.memorial', map: 'lf.sluice', at: [10, 11, 'up'], flags: LT, expect: { pc: ['observe', 'kneel'] },
    variants: [{ name: 'before the bell', comps: ALL4 }, { name: 'the names back', comp: 'mio', flags: LB, expect: { comp: ['kneel'] } }] },
  // 22_main.js
  { ch: 5, scene: 'lf.tadashi', map: 'lf.records', at: [7, 5, 'up'], talk: 'lf_tadashi', flags: LT,
    variants: [{ name: 'the form', comps: ALL4, quests: { lf_main: 0 }, expect: { lf_tadashi: ['nod', 'present', 'stamp', 'palm'], pc: ['observe'] } },
      { name: 'the slip in hand', comp: 'nao', quests: { lf_main: 1 }, items: { lf_request_slip: 1 }, expect: { lf_tadashi: ['palm'] } },
      { name: 'the ledger read', comp: 'mio', quests: { lf_main: 2 }, flags: F(LT, { lf_ledger_seen: true }), expect: { lf_tadashi: ['aside'], pc: ['palm'] } },
      { name: 'the ledger read · the key had', comp: 'ren', quests: { lf_main: 3 }, flags: F(LT, { lf_ledger_seen: true, lf_akari_key: true }) },
      { name: 'later', comp: 'suzu', quests: { lf_main: 5 }, expect: { lf_tadashi: ['halfraise'] } },
      { name: 'after Mio refused', comp: 'nao', quests: { lf_main: 5 }, flags: F(LT, { lf_mio_done: true }), expect: { lf_tadashi: ['chin', 'read'] } }] },
  { ch: 5, scene: 'lf.tadashi_after', map: 'lf.records', at: [7, 5, 'up'], talk: 'lf_tadashi', flags: LB,
    variants: [{ name: 'first', comps: ALL4, expect: { lf_tadashi: ['exhale', 'stamp'] } }, { name: 'again', comp: 'mio', seen: ['lf.tadashi_after'], expect: { lf_tadashi: ['palm', 'exhale'] } }] },
  { ch: 5, scene: 'lf.records_ledger', map: 'lf.records', at: [2, 7, 'down'], flags: LT, quests: { lf_main: 1 },
    variants: [{ name: 'with the slip', comps: ALL4, items: { lf_request_slip: 1 }, expect: { pc: ['read', 'observe'] } }, { name: 'no permit', comp: 'nao', expect: { pc: ['observe'] } }] },
  { ch: 5, scene: 'lf.akari_letters', map: 'lf.clerks', at: [5, 5, 'up'], talk: 'akari', flags: LT, quests: { lf_main: 2 }, expect: { akari: ['lowered', 'guard', 'fidget'], pc: ['observe'] },
    variants: [{ name: 'after Snowbell', comps: ALL4, expect: { akari: ['flinch'] } }, { name: 'before Snowbell', comp: 'mio', flags: F(LT, { ch4_done: false }), expect: { akari: ['lookroad'] } },
      { name: 'with Hoshino\'s letter', comp: 'ren', items: { sb_reply_letter: 1 }, flags: F(LT, { sb_hoshino_goes: true }), expect: { akari: ['receive', 'read'] } }] },
  { ch: 5, scene: 'lf.akari_reply', map: 'lf.clerks', at: [5, 5, 'up'], talk: 'akari', flags: LT, quests: { lf_main: 2, lf_akari: 0 }, items: { sb_reply_letter: 1 },
    expect: { akari: ['flinch', 'observe', 'receive', 'read', 'present', 'guard'], pc: ['present', 'handover'] },
    variants: [{ name: 'he goes · nao', comp: 'nao', flags: F(LT, { sb_hoshino_goes: true }) }, { name: 'both · mio', comp: 'mio', flags: F(LT, { sb_hoshino_both: true }) }, { name: 'he stays · ren', comp: 'ren' }, { name: 'he stays · suzu', comp: 'suzu' }] },
  { ch: 5, scene: 'lf.akari_hint', map: 'lf.clerks', at: [5, 5, 'up'], talk: 'akari', flags: LT, expect: { akari: ['guard', 'avert', 'present', 'handover'], pc: ['receive'] },
    variants: [{ name: 'the letters heard', comps: ALL4, quests: { lf_main: 2, lf_akari: 0 } }, { name: 'first the letters', comp: 'nao', quests: { lf_main: 2 } }] },
  { ch: 5, scene: 'lf.akari_letter', map: 'lf.clerks', at: [5, 5, 'up'], talk: 'akari', flags: LB, quests: { lf_akari: 1 }, expect: { akari: ['palm', 'avert', 'thanks'] },
    variants: [{ name: 'the reply had · he goes · nao', comp: 'nao', flags: F(LB, { lf_akari_got_reply: true, sb_hoshino_goes: true }), expect: { akari: ['handover'], comp: ['receive'] } },
      { name: 'both · mio', comp: 'mio', flags: F(LB, { lf_akari_got_reply: true, sb_hoshino_both: true }) }, { name: 'he stays · ren', comp: 'ren', flags: F(LB, { lf_akari_got_reply: true }) }, { name: 'no reply · suzu', comp: 'suzu' }] },
  { ch: 5, scene: 'lf.akari_post', map: 'lf.clerks', at: [5, 5, 'up'], talk: 'akari', flags: LP, expect: { akari: ['present'] },
    variants: [{ name: 'he went', comp: 'nao', flags: F(LP, { sb_hoshino_goes: true }) }, { name: 'he stayed', comp: 'suzu' }] },
  { ch: 5, scene: 'lf.stacks_enter', map: 'lf.stacks', at: [2, 3, 'down'], flags: F(LT, { lf_stacks_open: true }), quests: { lf_main: 3 }, comps: ALL4, expect: { pc: ['lookroad', 'cupear'] } },
  { ch: 5, scene: 'lf.minutes_chest', map: 'lf.stacks', at: [21, 3, 'up'], flags: F(LT, { lf_stacks_open: true }), quests: { lf_main: 3 }, comps: ALL4, expect: { pc: ['kneel', 'read'] } },
  { ch: 5, scene: 'lf.conduit', map: 'lf.stacks', at: [21, 7, 'right'], flags: F(LT, { lf_stacks_open: true }), quests: { lf_main: 3 }, expect: { pc: ['observe'] },
    variants: [{ name: 'first', comps: ALL4, expect: { pc: ['cupear', 'bend'] } }, { name: 'again', comp: 'nao', flags: F(LT, { lf_stacks_open: true, lf_conduit_seen: true }) }] },
  { ch: 5, scene: 'lf.yae', map: 'lf.council', at: [7, 3, 'left'], talk: 'lf_yae', flags: LT, quests: { lf_main: 2 }, comps: ['mio', 'suzu', 'nao'], expect: { lf_yae: ['palm', 'chin', 'nod', 'aside'] } },
  { ch: 5, scene: 'lf.yae_minutes', map: 'lf.council', at: [7, 3, 'left'], talk: 'lf_yae', flags: LT, quests: { lf_main: 4 }, items: { lf_minutes: 1 }, comps: ALL4, minLines: 15,
    expect: { lf_yae: ['receive', 'read', 'lowered', 'aside', 'palm', 'laugh'], pc: ['handover'] } },
  { ch: 5, scene: 'lf.tokuji_early', map: 'lf.sluice', at: [18, 11, 'left'], talk: 'lf_tokuji', flags: LT, quests: { lf_main: 2 }, comps: ALL4, expect: { lf_tokuji: ['lookroad'] } },
  { ch: 5, scene: 'lf.tokuji_story', map: 'lf.sluice', at: [18, 11, 'left'], talk: 'lf_tokuji', flags: F(LT, { lf_yae_told: true }), quests: { lf_main: 5 }, items: { lf_minutes: 1 }, comps: ALL4, minLines: 12,
    expect: { lf_tokuji: ['observe', 'lowered', 'present', 'handover', 'nod', 'folded', 'flinch'], pc: ['present', 'receive', 'wave'] } },
  { ch: 5, scene: 'lf.tokuji_post', map: 'lf.sluice', at: [18, 11, 'left'], talk: 'lf_tokuji', flags: LP,
    variants: [{ name: 'Kasane came', comp: 'nao', flags: F(LP, { end_kasane_trial: true }), expect: { lf_tokuji: ['lookroad'] } }, { name: 'the memories back', comp: 'ren', flags: F(LP, { end_mem_return: true, end_kasane_keeper: true }), expect: { lf_tokuji: ['nod'] } }] },
  { ch: 5, scene: 'lf.yae_after', map: 'lf.council', at: [7, 3, 'left'], talk: 'lf_yae', flags: F(LB, { lf_after_town: true }), quests: { lf_main: 7 },
    variants: [{ name: 'the council back', comps: ALL4, minLines: 14, expect: { lf_yae: ['emphatic', 'celebrate', 'present'], lf_tadashi: ['glasses', 'emphatic'], lf_masaru: ['celebrate'] } }, { name: 'later', comp: 'mio', flags: LD, expect: { lf_yae: ['laugh'] } }] },
  { ch: 5, scene: 'lf.after_town', map: 'lf.town', at: [39, 38, 'up'], flags: LB, comps: ALL4, minLines: 8, expect: { pc: ['lookroad', 'cupear'], lf_masaru: ['flinch'], lf_kohei: ['listen'] } },
  // 24_tower.js
  { ch: 5, scene: 'lf.tower_arrive', map: 'lf.tower_top', at: [7, 9, 'up'], flags: F(LT, { lf_yae_told: true, lf_tokuji_told: true, lf_tokuji_boat: true }), quests: { lf_main: 6 }, comps: ALL4, expect: { pc: ['observe', 'cupear'] } },
  { ch: 5, scene: 'lf.roster', map: 'lf.tower_top', at: [2, 3, 'up'], flags: LW, comps: ALL4, expect: { pc: ['observe', 'bend'] } },
  { ch: 5, scene: 'lf.wheel_upper', map: 'lf.tower_upper', at: [3, 5, 'left'], flags: LW, comp: 'nao',
    variants: [{ name: 'turn it', picks: [0], expect: { pc: ['observe', 'bend'] } }, { name: 'leave it', picks: [1] }, { name: 'closed already', flags: F(LW, { lf_up_closed: true }) }] },
  { ch: 5, scene: 'lf.wheel_lower', map: 'lf.tower_upper', at: [16, 9, 'right'], flags: F(LW, { lf_up_closed: true }),
    variants: [{ name: 'turned', picks: [0], comps: ALL4, expect: { pc: ['observe', 'bend', 'lookroad'] } }, { name: 'left', picks: [1], comp: 'mio', expect: { pc: ['observe'] } },
      { name: 'stuck · plate unread', picks: [0], comp: 'nao', flags: LW }, { name: 'stuck · plate read', picks: [0], comps: ALL4, flags: F(LW, { lf_plate_a_read: true }) }, { name: 'open already', comp: 'ren', flags: F(LW, { lf_up_closed: true, lf_gate_a: true }), expect: { pc: ['lookroad'] } }] },
  { ch: 5, scene: 'lf.mid_enter', map: 'lf.tower_mid', at: [10, 2, 'down'], flags: F(LW, { lf_up_closed: true, lf_gate_a: true }), comps: ALL4, expect: { pc: ['observe', 'lookroad', 'bend'] } },
  { ch: 5, scene: 'lf.east_door', map: 'lf.tower_mid', at: [19, 8, 'right'], flags: LM, expect: { pc: ['observe'] },
    variants: [{ name: 'open it', picks: [0], comp: 'nao', expect: { pc: ['bend'] } }, { name: 'leave it shut', picks: [1], comp: 'mio' },
      { name: 'shut it again', picks: [0], comp: 'ren', flags: F(LM, { lf_east_open: true }) }, { name: 'drained · seal it', picks: [0], comps: ALL4, flags: F(LM, { lf_east_open: true, lf_mid_drained: true }) },
      { name: 'drained · leave it open', picks: [1], comp: 'suzu', flags: F(LM, { lf_east_open: true, lf_mid_drained: true }) }, { name: 'barred', comp: 'nao', flags: F(LM, { lf_gate_b: true }) }] },
  { ch: 5, scene: 'lf.west_plug', map: 'lf.tower_mid', at: [2, 8, 'left'], flags: LM, expect: { pc: ['observe'] },
    variants: [{ name: 'pulled', picks: [0], comp: 'mio', flags: F(LM, { lf_east_open: true }), expect: { pc: ['bend', 'lookroad'] } }, { name: 'stuck · plate unread', picks: [0], comp: 'nao' },
      { name: 'stuck · plate read', picks: [0], comp: 'ren', flags: F(LM, { lf_plate_b_read: true }) }, { name: 'leave it', picks: [1], comp: 'suzu' }, { name: 'out already', comp: 'nao', flags: F(LM, { lf_east_open: true, lf_mid_drained: true }) }] },
  { ch: 5, scene: 'lf.water_returns', map: 'lf.tower_mid', at: [10, 10, 'down'], flags: F(LM, { lf_east_open: true, lf_mid_drained: true }), comps: ALL4, expect: { pc: ['flinch', 'lookroad'] } },
  { ch: 5, scene: 'lf.junction', map: 'lf.tower_mid', at: [18, 4, 'right'], flags: LM, expect: { pc: ['cupear'] },
    variants: [{ name: 'first', comps: ALL4, expect: { pc: ['observe', 'lookroad', 'receive'] } }, { name: 'again', comp: 'mio', flags: F(LM, { lf_koe: true }) }] },
  { ch: 5, scene: 'lf.low_enter', map: 'lf.tower_low', at: [10, 2, 'down'], flags: LL, comps: ALL4, expect: { pc: ['lookroad', 'listen'] } },
  { ch: 5, scene: 'lf.south_plug', map: 'lf.tower_low', at: [3, 14, 'left'], flags: LL, comp: 'nao', expect: { pc: ['observe'] },
    variants: [{ name: 'pulled', picks: [0], expect: { pc: ['bend', 'lookroad'] } }, { name: 'leave it', picks: [1] }, { name: 'out already', flags: F(LL, { lf_south_pulled: true }) }] },
  { ch: 5, scene: 'lf.north_plug', map: 'lf.tower_low', at: [15, 3, 'right'], flags: LL, expect: { pc: ['observe'] },
    variants: [{ name: 'pulled', picks: [0], comps: ALL4, flags: F(LL, { lf_south_pulled: true }), expect: { pc: ['bend', 'lookroad'] } }, { name: 'too soon', picks: [0], comps: ALL4, expect: { pc: ['flinch', 'brow'] } },
      { name: 'leave it', picks: [1], comp: 'mio' }, { name: 'out already', comp: 'ren', flags: F(LL, { lf_south_pulled: true, lf_gate_c: true }) }] },
  { ch: 5, scene: 'lf.waterline', map: 'lf.tower_low', at: [14, 6, 'up'], flags: LL, comps: ALL4, expect: { pc: ['observe'] } },
  { ch: 5, scene: 'lf.boss_intro', map: 'lf.bellhall', at: [8, 5, 'down'], flags: F(LL, { lf_south_pulled: true, lf_gate_c: true }), quests: { lf_main: 7 }, comps: ALL4, minLines: 4, expect: { pc: ['flinch', 'observe'] } },
  { ch: 5, scene: 'lf.tower_key', map: 'lf.bellhall', at: [9, 3, 'up'], flags: F(LL, { lf_south_pulled: true, lf_gate_c: true, lf_boss_done: true }), comps: ALL4, expect: { pc: ['observe', 'bend'] } },
  // 26_side.js
  { ch: 5, scene: 'lf.fence_talk', map: 'lf.gardens', at: [10, 8, 'up'], talk: 'lf_kohei', flags: LT,
    variants: [{ name: 'first', comps: ALL4, expect: { lf_kohei: ['point', 'nod', 'shrug'], lf_kinu: ['nod', 'point', 'stretch'], pc: ['observe'] } },
      { name: 'after the bell', comp: 'nao', flags: LB, expect: { lf_kinu: ['emphatic', 'laugh'], lf_kohei: ['folded', 'shrug'] } },
      { name: 'looking · before the bell', comp: 'mio', quests: { lf_fence: 0 }, expect: { lf_kohei: ['point'], lf_kinu: ['nod'] } },
      { name: 'looking · after the bell', comp: 'ren', quests: { lf_fence: 0 }, flags: LB, expect: { lf_kinu: ['laugh'] } },
      { name: 'the record', comps: ALL4, quests: { lf_fence: 1 }, expect: { pc: ['present', 'lookbetween'], lf_kohei: ['point'], lf_kinu: ['point'] } },
      { name: 'the record · again', comp: 'suzu', quests: { lf_fence: 2 }, expect: { lf_kohei: ['shrug'] } },
      { name: 'settled after the bell', comps: ALL4, quests: { lf_fence: 2 }, flags: LB, minLines: 12, expect: { lf_kinu: ['emphatic', 'chin', 'point', 'laugh', 'bend', 'present'], lf_kohei: ['folded', 'chin', 'shrug', 'nod', 'bend'], pc: ['size'] } }] },
  { ch: 5, scene: 'lf.hayato', map: 'lf.records', at: [10, 6, 'up'], talk: 'lf_hayato', flags: LT, expect: { lf_hayato: ['nod', 'present', 'lowered', 'handover'], pc: ['receive'] },
    variants: [{ name: 'before the bell', comps: ALL4, expect: { lf_hayato: ['aside'], pc: ['write'] } }, { name: 'after the bell', comp: 'nao', flags: LB, expect: { lf_hayato: ['emphatic', 'write'] } }] },
  { ch: 5, scene: 'lf.tsuya', map: 'lf.town', at: [40, 32, 'down'], talk: 'lf_tsuya', flags: LT,
    variants: [{ name: 'first', comps: ALL4, expect: { lf_tsuya: ['lookroad', 'chin', 'laugh', 'nod'], pc: ['point'] } }, { name: 'waiting', comp: 'nao', quests: { lf_timetable: 0 }, expect: { lf_tsuya: ['lookroad'] } },
      { name: 'told · before the bell', comp: 'mio', quests: { lf_timetable: 1 }, expect: { lf_tsuya: ['listen', 'nod'], pc: ['palm'] } },
      { name: 'told · after the bell', comps: ALL4, quests: { lf_timetable: 1 }, flags: LB, expect: { lf_tsuya: ['lookroad', 'laugh'] } }] },
  { ch: 5, scene: 'lf.timetable', map: 'lf.ferry', at: [7, 3, 'up'], flags: LT, expect: { pc: ['observe'] },
    variants: [{ name: 'no errand', comp: 'nao', expect: { pc: ['bend'] } }, { name: 'ask for the log', comp: 'mio', quests: { lf_timetable: 0 }, picks: [0], expect: { umi: ['handover', 'fidget', 'lowered'], pc: ['receive'] } },
      { name: 'leave it', comp: 'ren', quests: { lf_timetable: 0 }, picks: [1] }, { name: 'after the bell', comp: 'suzu', quests: { lf_timetable: 0 }, flags: LB, expect: { pc: ['bend'], umi: ['present'] } }] },
  { ch: 5, scene: 'lf.umi', map: 'lf.ferry', at: [4, 4, 'up'], talk: 'umi', flags: LT, expect: { umi: ['palm', 'nod', 'fidget'] },
    variants: [{ name: 'nao', comp: 'nao', quests: { lf_nao: 1 }, expect: { comp: ['strap'] } }, { name: 'mio', comp: 'mio' }, { name: 'suzu', comp: 'suzu' }] },
  { ch: 5, scene: 'lf.umi_after', map: 'lf.ferry', at: [4, 4, 'up'], talk: 'umi', flags: LB, expect: { umi: ['emphatic'] },
    variants: [{ name: 'the letter came · mio', comp: 'mio', expect: { umi: ['present'] } }, { name: 'nao delivered', comp: 'nao', quests: { lf_nao: 'done' }, expect: { umi: ['palm'], comp: ['nod'] } }] },
  // 28_companions.js
  { ch: 5, scene: 'lf.nao_umi_first', map: 'lf.ferry', at: [4, 4, 'up'], talk: 'umi', comp: 'nao', flags: LT, quests: { lf_nao: 0 }, minLines: 15,
    expect: { umi: ['palm', 'flinch', 'receive'], comp: ['strap', 'palm', 'present', 'emphatic', 'lowered', 'exhale', 'nod'] } },
  { ch: 5, scene: 'lf.nao_deliver', map: 'lf.ferry', at: [4, 4, 'up'], talk: 'umi', comp: 'nao', flags: LB, quests: { lf_nao: 1 }, minLines: 25,
    expect: { umi: ['emphatic', 'observe', 'receive', 'read', 'lowered', 'write', 'handover'], comp: ['avert', 'present', 'handover', 'lookbetween', 'receive', 'point', 'write', 'check', 'aside'] },
    variants: [{ name: 'met before', seen: ['lf.nao_umi_first'] }, { name: 'first meeting', expect: { umi: ['flinch'], comp: ['strap'] } }] },
  { ch: 5, scene: 'lf.naoc', map: 'lf.town', at: [39, 31, 'up'], talk: 'nao', flags: LT, comps: ['mio', 'ren', 'suzu'], expect: { nao: ['nod', 'point', 'lookbetween', 'strap', 'aside'] } },
  { ch: 5, scene: 'lf.naoc_after', map: 'lf.town', at: [39, 31, 'up'], talk: 'nao', flags: LB, comps: ['mio', 'ren', 'suzu'], expect: { nao: ['nod', 'present', 'point', 'wave'] } },
  { ch: 5, scene: 'lf.mio_start', map: 'lf.town', at: [11, 11, 'down'], comp: 'mio', flags: F(LT, { lf_ledger_seen: true }), quests: { lf_main: 2 }, minLines: 15,
    expect: { comp: ['nod', 'fidget', 'write', 'guard', 'receive', 'recoil', 'present', 'shake', 'lowered', 'lookroad'], lf_hayato: ['handover'] } },
  { ch: 5, scene: 'lf.mioc', map: 'lf.inn', at: [4, 7, 'left'], talk: 'mio', flags: LT, comps: ['nao', 'ren', 'suzu'], expect: { mio: ['nod', 'palm', 'guard', 'laugh'] } },
  { ch: 5, scene: 'lf.mioc_after', map: 'lf.inn', at: [4, 7, 'left'], talk: 'mio', flags: LB, comps: ['nao', 'ren', 'suzu'], expect: { mio: ['celebrate', 'laugh', 'check'] } },
];

// ---- Chapter 6: the Still Archive ----------------------------------------------------------------------------
const S0 = F(LD, { sa_arrived: true }); // on the Archive road
const SC = F(S0, { 'enter:sa.camp:sa.camp_first': true }); // the camp
const SR = F(S0, { sa_met_kasane: true, sa_kasane_left: true }); // inside, after meeting Kasane
const SK = F(SR, { sa_catalogue_done: true }); // the Stacks open
const SN = F(SK, { sa_stacks_done: true }); // the Conduits
const SM = F(SN, { sa_promise_done: true }); // the Room of Set-Down Memories and the study
const SH = F(SM, { sa_shortcut: true }); // up to the Heart
const SB = F(SH, { sa_hush_down: true }); // the Hush down
const ST = F(SB, { sa_toya_read: true }); // Tōya's note read: the three decisions
const SD = F(ST, { sa_choice_mem: true, sa_choice_archive: true, sa_choice_kasane: true, sa_descent: true }); // the way down
const SDT = F(SD, { end_mem_return: true, end_archive_library: true, end_kasane_trial: true }); // one set of decisions
const SDK = F(SD, { end_mem_choose: true, end_archive_closed: true, end_kasane_keeper: true }); // the other
const SE = F(SDT, { sa_epilogue: true, sb_evening: true, co_restored: true, co_bell_done: true, rw_echo_done: true, rw_koji_back: true }); // the epilogue
const SP = F(SDT, { sa_done: true, ch6_done: true, post: true, postgame: true }); // after the ending
const SPK = F(SDK, { sa_done: true, ch6_done: true, post: true, postgame: true });
const CH6 = [
  // 50_scenes_road.js
  { ch: 6, scene: 'sa.arrive', map: 'sa.road', at: [2, 23, 'up'], flags: LD, comps: ALL4, minLines: 5, expect: { pc: ['lookroad', 'observe'] } },
  { ch: 6, scene: 'sa.lantern1', map: 'sa.road', at: [5, 21, 'up'], flags: S0, comps: ALL4, expect: { pc: ['observe', 'bend'] } },
  { ch: 6, scene: 'sa.lantern2', map: 'sa.road', at: [22, 21, 'up'], flags: S0, comps: ['suzu', 'ren', 'nao'], expect: { pc: ['observe'] } },
  { ch: 6, scene: 'sa.lantern3', map: 'sa.road', at: [12, 15, 'up'], flags: S0, comps: ['mio', 'nao', 'ren'], expect: { pc: ['observe'] } },
  { ch: 6, scene: 'sa.lantern4', map: 'sa.road', at: [30, 4, 'left'], flags: S0, comps: ALL4, expect: { pc: ['observe'] } },
  { ch: 6, scene: 'sa.road_marker', map: 'sa.road', at: [10, 22, 'down'], flags: S0, comps: ALL4, expect: { pc: ['observe', 'bend'] } },
  { ch: 6, scene: 'sa.road_bundle', map: 'sa.road', at: [25, 9, 'up'], flags: S0, comps: ALL4, expect: { pc: ['bend'] } },
  { ch: 6, scene: 'sa.camp_first', map: 'sa.camp', at: [13, 17, 'up'], flags: S0, comps: ALL4, expect: { pc: ['lookroad', 'observe'] } },
  { ch: 6, scene: 'sa.camp_board', map: 'sa.camp', at: [9, 14, 'up'], flags: SC, comps: ALL4, expect: { pc: ['observe'] } },
  { ch: 6, scene: 'sa.hut_register_signed', map: 'sa.hut', at: [4, 5, 'up'], flags: SC, comps: ALL4, expect: { pc: ['write'] } },
  { ch: 6, scene: 'sa.oyone_first', map: 'sa.hut', at: [3, 3, 'up'], talk: 'sa_oyone', flags: SC, comps: ALL4, picks: [1], minLines: 6, expect: { sa_oyone: ['point', 'chin', 'lowered'] } },
  { ch: 6, scene: 'sa.oyone_inn', map: 'sa.hut', at: [3, 3, 'up'], talk: 'sa_oyone', flags: SC, seen: ['sa.oyone_first'], comp: 'mio',
    variants: [{ name: 'rest', picks: [0], expect: { sa_oyone: ['tendlight', 'observe'] } }, { name: 'not now', picks: [1], expect: { sa_oyone: ['nod'] } }] },
  { ch: 6, scene: 'sa.ushio_grave', map: 'sa.gate', at: [22, 19, 'up'], flags: SR, expect: { pc: ['observe', 'bend'] },
    variants: [{ name: 'without Ren', comps: ['nao', 'mio', 'suzu'] }, { name: 'Ren', comp: 'ren', expect: { comp: ['observe', 'lowered', 'tendlamp', 'nod'] } }, { name: 'seen before', comp: 'nao', seen: ['sa.ushio_grave'] }] },
  { ch: 6, scene: 'sa.gate_first', map: 'sa.gate', at: [14, 19, 'up'], flags: S0, comps: ALL4, expect: { pc: ['lookroad', 'cupear', 'lookbetween'] } },
  // 51_scenes_archive.js
  { ch: 6, scene: 'sa.kasane_meet', map: 'sa.reading', at: [14, 17, 'up'], flags: S0, minLines: 20, expect: { kasane: ['palm', 'nod', 'lowered', 'point'], pc: ['lookroad'] },
    variants: [{ name: 'without being asked?', comps: ALL4, picks: [0] }, { name: 'why arguments?', comp: 'ren', picks: [1] }] },
  { ch: 6, scene: 'sa.clerk_first', map: 'sa.reading', at: [6, 5, 'up'], talk: 'sa_clerk', flags: SR, comps: ALL4, minLines: 10, expect: { sa_clerk: ['stiff'], pc: ['observe'] } },
  { ch: 6, scene: 'sa.clerk_name', map: 'sa.reading', at: [6, 5, 'up'], talk: 'sa_clerk', flags: SM, items: { sa_ushio_notes: 1 }, quests: { sa_clerk: 0 }, expect: { pc: ['present'], sa_clerk: ['listen'] },
    variants: [{ name: 'met · named', comps: ALL4, seen: ['sa.clerk_first'], expect: { pc: ['observe', 'receive'] } }, { name: 'first meeting · named', comp: 'nao', expect: { sa_clerk: ['stiff'] } }, { name: 'not yet', comp: 'mio', seen: ['sa.clerk_first'], fail: true, expect: { sa_clerk: ['stiff'] } }] },
  { ch: 6, scene: 'sa.cabinet', map: 'sa.reading', at: [3, 3, 'up'], flags: SR, quests: { sa_main: 1 }, expect: { pc: ['observe'] },
    variants: [{ name: 'sorted', comps: ALL4, expect: { pc: ['lookroad'], sa_clerk: ['stiff'] } }, { name: 'not yet', comp: 'nao', fail: true }] },
  { ch: 6, scene: 'sa.reading_desk', map: 'sa.reading', at: [7, 6, 'down'], flags: SR, comps: ALL4, expect: { pc: ['observe', 'bend'] } },
  { ch: 6, scene: 'sa.stacks_enter', map: 'sa.stacks', at: [29, 12, 'left'], flags: SK, quests: { sa_main: 2 }, comps: ALL4, expect: { pc: ['lookroad', 'observe'] } },
  { ch: 6, scene: 'sa.stacks_gate', map: 'sa.stacks', at: [14, 18, 'down'], flags: SK, quests: { sa_main: 2 },
    variants: [{ name: 'read the slip', comps: ALL4, seen: ['sa.stacks_slip'], expect: { pc: ['observe', 'lookroad'] } }, { name: 'no slip yet', comp: 'nao', expect: { pc: ['lookroad'] } },
      { name: 'not yet', comp: 'mio', seen: ['sa.stacks_slip'], fail: true, expect: { pc: ['observe'] } }, { name: 'open', comp: 'ren', flags: SN, expect: { pc: ['lookroad'] } }] },
  { ch: 6, scene: 'sa.conduits_enter', map: 'sa.conduits', at: [27, 4, 'down'], flags: SN, quests: { sa_main: 3 }, comps: ALL4, expect: { pc: ['lookroad', 'cupear'] } },
  { ch: 6, scene: 'sa.notice_desk', map: 'sa.conduits', at: [2, 5, 'up'], flags: SN, quests: { sa_main: 3 }, expect: { pc: ['observe'] },
    variants: [{ name: 'found', comps: ALL4, expect: { pc: ['bend'] } }, { name: 'taken', comp: 'nao', items: { sa_notice: 1 } }] },
  { ch: 6, scene: 'sa.charter_gate', map: 'sa.conduits', at: [3, 13, 'down'], flags: SN, quests: { sa_main: 3 }, expect: { pc: ['observe'] },
    variants: [{ name: 'read rightly', comps: ALL4, expect: { pc: ['bend', 'lookroad'] } }, { name: 'not yet', comp: 'mio', fail: true }, { name: 'open', comp: 'ren', flags: SM }] },
  { ch: 6, scene: 'sa.conduit_crate', map: 'sa.conduits', at: [27, 15, 'down'], flags: SN, comps: ALL4, expect: { pc: ['bend', 'read'] } },
  { ch: 6, scene: 'sa.memories_enter', map: 'sa.memories', at: [21, 9, 'left'], flags: SM, quests: { sa_main: 4 }, comps: ['nao', 'mio', 'suzu'], expect: { pc: ['lookroad', 'observe'] } },
  { ch: 6, scene: 'sa.mem_requests', map: 'sa.memories', at: [9, 14, 'up'], flags: SM, comps: ALL4, expect: { pc: ['observe', 'read'] } },
  { ch: 6, scene: 'sa.shelf_kasane', map: 'sa.memories', at: [3, 4, 'up'], flags: SM,
    variants: [{ name: 'opened', comps: ALL4, expect: { pc: ['read'] } }, { name: 'asked for', comp: 'nao', flags: F(SB, { sa_need_letter: true }) }, { name: 'taken', comp: 'mio', items: { sa_letter_kasane: 1 }, expect: { pc: ['observe'] } }] },
  { ch: 6, scene: 'sa.shelf_returned_rw', map: 'sa.memories', at: [6, 4, 'up'], flags: SM, comps: ['mio', 'nao'], expect: { pc: ['observe'] } },
  { ch: 6, scene: 'sa.shelf_returned_co', map: 'sa.memories', at: [15, 4, 'up'], flags: SM, expect: { pc: ['observe'] },
    variants: [{ name: 'still there', comp: 'nao' }, { name: 'returned', comp: 'suzu', flags: F(SM, { co_restored: true }), expect: { comp: ['lowered'] } }] },
  { ch: 6, scene: 'sa.shelf_returned_lf', map: 'sa.memories', at: [7, 7, 'up'], flags: SM, comps: ['mio', 'nao'], expect: { pc: ['observe'] } },
  { ch: 6, scene: 'sa.shelf_tae', map: 'sa.memories', at: [16, 7, 'up'], flags: SM, expect: { pc: ['observe'] },
    variants: [{ name: 'the slip', comps: ALL4, expect: { pc: ['read'] } }, { name: 'taken', comp: 'ren', items: { sa_tae_slip: 1 } }] },
  { ch: 6, scene: 'sa.shelf_grief2', map: 'sa.memories', at: [6, 13, 'up'], flags: SM, comps: ['suzu', 'nao'], expect: { pc: ['observe', 'bend'] } },
  { ch: 6, scene: 'sa.shelf_empty', map: 'sa.memories', at: [5, 16, 'up'], flags: SM, comps: ALL4, expect: { pc: ['observe', 'bend'] } },
  { ch: 6, scene: 'sa.shelf_isamu', map: 'sa.memories', at: [3, 13, 'up'], flags: SM,
    variants: [{ name: 'found', comps: ALL4, quests: { sa_isamu: 0 }, expect: { pc: ['observe', 'read'] } }, { name: 'not found', comp: 'nao', quests: { sa_isamu: 0 }, fail: true, expect: { pc: ['observe'] } },
      { name: 'no errand', comp: 'mio', expect: { pc: ['observe'] } }, { name: 'carrying it', comp: 'ren', quests: { sa_isamu: 1 }, items: { sa_folio_isamu: 1 } }, { name: 'returned', comp: 'suzu', quests: { sa_isamu: 'done' }, expect: { pc: ['observe'] } }] },
  { ch: 6, scene: 'sa.study_enter', map: 'sa.study', at: [7, 9, 'up'], flags: SM, quests: { sa_main: 4 }, comps: ALL4, expect: { pc: ['lookroad', 'observe'] } },
  { ch: 6, scene: 'sa.study_desk', map: 'sa.study', at: [5, 4, 'up'], flags: SM,
    variants: [{ name: 'the slip', comps: ALL4, expect: { pc: ['bend', 'read'] } }, { name: 'taken', comp: 'nao', items: { sa_toya_reply: 1 }, expect: { pc: ['observe'] } }] },
  { ch: 6, scene: 'sa.study_objections', map: 'sa.study', at: [2, 3, 'up'], flags: SM, comps: ALL4, expect: { pc: ['observe', 'read'] } },
  { ch: 6, scene: 'sa.study_notebook', map: 'sa.study', at: [3, 3, 'up'], flags: SM,
    variants: [{ name: 'no errand', comp: 'nao', expect: { pc: ['bend', 'read'] } }, { name: 'for the clerk · Ren', comp: 'ren', quests: { sa_clerk: 0 }, expect: { comp: ['tendlamp'] } },
      { name: 'for the clerk · Mio', comp: 'mio', quests: { sa_clerk: 0 }, expect: { pc: ['lookroad'] } }, { name: 'taken', comp: 'suzu', items: { sa_ushio_notes: 1 }, expect: { pc: ['observe'] } }] },
  { ch: 6, scene: 'sa.study_cups', map: 'sa.study', at: [12, 7, 'down'], flags: SM, comps: ALL4, expect: { pc: ['observe', 'bend'] } },
  { ch: 6, scene: 'sa.shortcut_open', map: 'sa.study', at: [1, 6, 'left'], flags: SM, comps: ['nao', 'ren'], expect: { pc: ['observe', 'bend'] } },
  // 52_scenes_climax.js
  { ch: 6, scene: 'sa.heart_enter', map: 'sa.heart', at: [12, 17, 'up'], flags: SH, quests: { sa_main: 6 }, comps: ALL4, expect: { pc: ['lookroad', 'observe'] } },
  { ch: 6, scene: 'sa.heart_kasane', map: 'sa.heart', at: [12, 11, 'up'], flags: SH, quests: { sa_main: 6 }, minLines: 3,
    variants: [{ name: 'you are wrong', comps: ALL4, picks: [0], expect: { kasane: ['nod', 'palm', 'lowered', 'recoil'] } }, { name: 'Tōya\'s note', comp: 'nao', picks: [1], expect: { kasane: ['nod', 'palm', 'aside', 'recoil'] } },
      { name: 'again · go', comp: 'mio', seen: ['sa.heart_kasane'], picks: [0], expect: { kasane: ['observe'] } }, { name: 'again · wait', comp: 'ren', seen: ['sa.heart_kasane'], picks: [1], expect: { kasane: ['observe', 'point'] } }] },
  { ch: 6, scene: 'sa.after_battle', map: 'sa.heart', at: [12, 11, 'up'], flags: SB, quests: { sa_main: 6 }, minLines: 10, expect: { pc: ['observe', 'cupear', 'point'], kasane: ['lookroad', 'lowered', 'avert'] },
    variants: [{ name: 'after the council', comps: ALL4, seen: ['lf.yae_after'], expect: { kasane: ['flinch'] } }, { name: 'without the message', comp: 'mio' }] },
  { ch: 6, scene: 'sa.choose_mem', map: 'sa.memories', at: [11, 10, 'down'], talk: 'kasane', flags: ST, quests: { sa_main: 7 }, expect: { kasane: ['palm', 'lowered', 'point', 'nod'] },
    variants: [{ name: 'return them', comps: ALL4, picks: [0], expect: { kasane: ['lookroad'] } }, { name: 'keep them', comps: ['nao', 'mio', 'suzu'], picks: [1] },
      { name: 'keep them · Ren took the face', comp: 'ren', flags: F(ST, { sa_ren_took: true }), picks: [1] }, { name: 'keep them · Ren left it', comp: 'ren', flags: F(ST, { sa_ren_left: true }), picks: [1] }] },
  { ch: 6, scene: 'sa.choose_archive', map: 'sa.reading', at: [14, 7, 'up'], talk: 'kasane', flags: F(ST, { sa_choice_mem: true, end_mem_return: true }), quests: { sa_main: 7 }, expect: { kasane: ['lookbetween', 'palm', 'point'] },
    variants: [{ name: 'a library', comps: ALL4, picks: [0], expect: { sa_clerk: ['stiff'] } }, { name: 'closed', comps: ALL4, picks: [1], expect: { kasane: ['lowered'], sa_clerk: ['stiff'] } },
      { name: 'Tsuzuri named · library', comp: 'nao', flags: F(ST, { sa_choice_mem: true, end_mem_return: true, sa_clerk_named: true }), picks: [0], expect: { sa_tsuzuri: ['stiff'] } }] },
  { ch: 6, scene: 'sa.choose_kasane', map: 'sa.gate', at: [15, 13, 'up'], talk: 'kasane', flags: F(ST, { sa_choice_mem: true, sa_choice_archive: true, end_mem_return: true, end_archive_library: true }), quests: { sa_main: 8 }, expect: { kasane: ['lookroad', 'lowered', 'nod'] },
    variants: [{ name: 'go down', comps: ALL4, picks: [0] }, { name: 'stay', comps: ALL4, picks: [1] },
      { name: 'the empty shelf seen · closed · stay', comp: 'mio', seen: ['sa.shelf_empty'], flags: F(ST, { sa_choice_mem: true, sa_choice_archive: true, end_mem_return: true, end_archive_closed: true }), picks: [1], expect: { kasane: ['avert'], pc: ['palm'] } }] },
  // 53_scenes_ending.js
  { ch: 6, scene: 'sa.camp_descent', map: 'sa.camp', at: [13, 16, 'down'], minLines: 4,
    variants: [{ name: 'Kasane comes down · Isamu helped', comps: ALL4, flags: SDT, quests: { sa_isamu: 'done' }, seen: ['sa.isamu_first'], expect: { sa_oyone: ['lookroad', 'observe', 'point'], kasane: ['avert'], sa_isamu: ['cupear'] } },
      { name: 'Kasane stays · Isamu waiting', comp: 'ren', flags: SDK, quests: { sa_isamu: 0 }, seen: ['sa.isamu_first'], expect: { sa_oyone: ['nod', 'write'], sa_isamu: ['cupear', 'exhale', 'lookroad'] } },
      { name: 'Isamu never met', comp: 'nao', flags: SDK, expect: { sa_oyone: ['lookroad'] } }] },
  { ch: 6, scene: 'sa.kasane_walk', map: 'sa.camp', at: [15, 15, 'right'], talk: 'kasane', flags: SDT, comps: ['mio', 'nao'], expect: { kasane: ['lookroad'] } },
  { ch: 6, scene: 'sa.epi_lf', map: 'lf.town', at: [2, 17, 'right'], minLines: 8, expect: { pc: ['lookroad', 'cupear', 'palm'], sa_tae: ['cupear', 'lowered', 'listen'] },
    variants: [{ name: 'Kasane came down · Mio', comp: 'mio', flags: F(SE, { sb_hoshino_goes: true }), expect: { kasane: ['bow'], lf_yae: ['laugh'], comp: ['bow', 'laugh'], akari: ['lookroad'] } },
      { name: 'Kasane stayed · Nao delivered', comp: 'nao', flags: F(SE, SDK, { lf_nao_cameo_done: true }), quests: { lf_nao: 'done' }, expect: { umi: ['palm'], comp: ['nod'] } },
      { name: 'Nao came back too soon', comp: 'nao', flags: F(SE, { lf_nao_cameo_done: true }), quests: { lf_nao: 1 }, expect: { comp: ['strap'] } },
      { name: 'Nao\'s letter undelivered', comp: 'nao', flags: F(SE, { lf_nao_cameo_done: true }), expect: { comp: ['strap'] } },
      { name: 'Ren', comp: 'ren', flags: SE }, { name: 'Suzu', comp: 'suzu', flags: SE }] },
  { ch: 6, scene: 'sa.epi_sb', map: 'sb.hamlet', at: [22, 33, 'up'], expect: { pc: ['lookroad'] },
    variants: [{ name: 'the lamp lit early · Ren took the face', comp: 'ren', flags: F(SE, { sa_ren_took: true }), expect: { hoshino: ['lookroad'], pc: ['shadeeyes'] } }, { name: 'Hoshino went down · Ren left it', comp: 'ren', flags: F(SE, { sb_hoshino_goes: true }), expect: { kanta: ['nod'] } },
      { name: 'nao', comp: 'nao', flags: SE }, { name: 'mio', comp: 'mio', flags: F(SE, SDK) }, { name: 'suzu', comp: 'suzu', flags: SE }] },
  { ch: 6, scene: 'sa.epi_co', map: 'co.village', at: [3, 18, 'right'], flags: F(SE, { co_chronicle_read: true }), expect: { pc: ['lookroad'] },
    variants: [{ name: 'suzu', comp: 'suzu', expect: { comp: ['lowered', 'nod'] } }, { name: 'nao', comp: 'nao' }, { name: 'mio · the seat named', comp: 'mio', flags: F(SE, { co_chronicle_read: true, co_hiro_seat_named: true }) }, { name: 'ren · no bell yet', comp: 'ren', flags: F(SE, { co_chronicle_read: true, co_bell_done: false }) }] },
  { ch: 6, scene: 'sa.epi_sg', map: 'sg.harbor', at: [27, 3, 'down'], flags: SE, expect: { pc: ['lookroad'], wataru: ['exhale'] },
    variants: [{ name: 'Isamu helped · mio', comp: 'mio', quests: { sa_isamu: 'done' }, expect: { sa_isamu: ['cupear'], nao: ['present'] } }, { name: 'nao', comp: 'nao' }, { name: 'ren', comp: 'ren' }, { name: 'suzu', comp: 'suzu' }] },
  { ch: 6, scene: 'sa.epi_rw', map: 'rw.village', at: [22, 30, 'up'], flags: SE, expect: { pc: ['lookroad'], hana: ['present'], tsuru: ['point'] },
    variants: [{ name: 'mio', comp: 'mio' }, { name: 'ren', comp: 'ren' }, { name: 'nao · Ren at home', comp: 'nao', flags: F(SE, { sa_ushio_found: true }), items: { sa_ren_folio: 1 }, expect: { ren: ['lowered', 'receive', 'read', 'thanks'] } }] },
  { ch: 6, scene: 'sa.epi_ren_home', map: 'rw.village', at: [22, 30, 'up'], flags: SE,
    variants: [{ name: 'the folio carried', comp: 'nao', flags: F(SE, { sa_ushio_found: true }), items: { sa_ren_folio: 1 }, expect: { pc: ['palm', 'handover'], ren: ['lowered', 'receive', 'read', 'thanks'] } },
      { name: 'told of the folio', comp: 'mio', flags: F(SE, { sa_ushio_found: true, sa_ren_told: true }), expect: { ren: ['lowered', 'cupear'] } },
      { name: 'the grave only', comp: 'suzu', flags: F(SE, { sa_ushio_found: true }), expect: { ren: ['lowered', 'tendlamp'] } },
      { name: 'no news', comp: 'nao', expect: { ren: ['palm'] } }] },
  { ch: 6, scene: 'sa.end_comp', map: 'rw.village', at: [22, 30, 'up'], flags: SE,
    variants: [{ name: 'nao', comp: 'nao', expect: { comp: ['bend', 'point', 'present', 'aside', 'handover', 'lookbetween', 'nod'], pc: ['receive', 'read'] } },
      { name: 'mio', comp: 'mio', expect: { comp: ['point', 'laugh', 'present', 'handover', 'shake'], pc: ['receive'] } },
      { name: 'ren · took the face', comp: 'ren', flags: F(SE, { sa_ren_took: true }), expect: { comp: ['tendlamp', 'present', 'lowered', 'palm', 'chin', 'nod'] } },
      { name: 'ren · left it', comp: 'ren', flags: F(SE, { sa_ren_left: true }), expect: { comp: ['aside'] } },
      { name: 'suzu', comp: 'suzu', expect: { comp: ['check', 'point', 'chin', 'exhale', 'present', 'handover'], pc: ['receive'] } },
      { name: 'alone', comp: null, expect: { pc: ['cupear'] } }] },
  // 54_scenes_side.js
  { ch: 6, scene: 'sa.isamu_first', map: 'sa.camp', at: [15, 11, 'right'], talk: 'sa_isamu', flags: SC, comps: ALL4, minLines: 8, expect: { sa_isamu: ['lookroad', 'cupear', 'lowered', 'rubhands', 'nod', 'exhale'], pc: ['observe'] } },
  { ch: 6, scene: 'sa.oyone_post', map: 'sa.hut', at: [3, 3, 'up'], talk: 'sa_oyone', comp: 'nao', expect: { sa_oyone: ['point'] },
    variants: [{ name: 'Kasane in Lanternfall', flags: SP, picks: [1], expect: { sa_oyone: ['nod'] } }, { name: 'Kasane kept the Archive', flags: SPK, picks: [0] }] },
  { ch: 6, scene: 'sa.kasane_post', map: 'sa.gate', at: [15, 13, 'up'], talk: 'kasane', flags: SPK, comp: 'mio', expect: { kasane: ['palm', 'present'] },
    variants: [{ name: 'at the shut gate · another time', picks: [1], expect: { kasane: ['lookroad'] } }, { name: 'at the shut gate · tell it', picks: [0], expect: { kasane: ['nod'] } },
      { name: 'in the library', map: 'sa.reading', at: [14, 6, 'up'], flags: F(SPK, { end_archive_closed: false, end_archive_library: true }), picks: [1] }] },
  { ch: 6, scene: 'sa.clerk_post', map: 'sa.camp', at: [16, 7, 'up'], talk: 'sa_clerk', flags: SPK, comp: 'ren', quests: { sa_clerk: 0 }, expect: { sa_clerk: ['stiff'] } },
];

export const CH56 = [...CH5, ...CH6];
