/* Companion shiritori: the table's interface words (Practice addendum §20; the
 * Japanese is shown when Settings › Interface language is Japanese). Kept here,
 * in a content registry, so the validator checks every kanji's furigana and
 * every word against the lexicon (tools/validate.mjs walks RB.content.wordplay). */
var RB = (globalThis.RB = globalThis.RB || {});
RB.content.wordplay = RB.content.wordplay || { lines: [], gestures: {}, reflections: {}, thoughts: [], texts: {} };

RB.content.wordplay.labels = {
  title: { jp: 'しりとり', en: 'Shiritori' },
  play: { jp: 'しりとり を する', en: 'Play shiritori' },
  resume: { jp: '{続|つづ}き から', en: 'Resume match' },
  endMatch: { jp: '{結果|けっか} なし で {終|お}える', en: 'End this match without a result' },
  start: { jp: '{始|はじ}める', en: 'Start' },
  rules: { jp: '{決|き}まり', en: 'Rules' },
  browse: { jp: '{言葉|ことば} の {一覧|いちらん}', en: 'Browse the word bank' },
  leave: { jp: '{離|はな}れる', en: 'Leave' },
  back: { jp: '{戻|もど}る', en: 'Back' },
  format: { jp: '{遊|あそ}び{方|かた}', en: 'Game' },
  competitive: { jp: '{勝負|しょうぶ} ・ {一局|いっきょく}', en: 'Competitive: one game' },
  cooperative: { jp: '{一緒|いっしょ} に {続|つづ}ける', en: 'Learning partner: cooperative' },
  words: { jp: '{言葉|ことば}', en: 'Words' },
  opponent: { jp: '{相手|あいて}', en: 'Opponent' },
  chain: { jp: '{目標|もくひょう} の {長|なが}さ', en: 'Chain to aim for' },
  support: { jp: '{手助|てだす}け', en: 'Support' },
  open: { jp: '{言葉|ことば} を {見|み}ながら', en: 'Open-book' },
  recall: { jp: '{思|おも}い{出|だ}して', en: 'Recall' },
  write: { jp: '{書|か}く', en: 'Write' },
  type: { jp: '{打|う}つ', en: 'Type' },
  choose: { jp: '{選|えら}ぶ', en: 'Choose' },
  playWord: { jp: 'この {言葉|ことば} で', en: 'Play word' },
  notWrote: { jp: '{書|か}いた {字|じ} と {違|ちが}う', en: 'That is not what I wrote' },
  clear: { jp: '{消|け}す', en: 'Clear' },
  stuck: { jp: '{困|こま}った {時|とき}', en: 'Stuck?' },
  find: { jp: '{言葉|ことば} を {探|さが}す', en: 'Find a word' },
  keep: { jp: 'もう {少|すこ}し {考|かんが}える', en: 'Keep thinking' },
  concede: { jp: '{降参|こうさん} する', en: 'Concede this game' },
  endChain: { jp: 'ここ で {終|お}える', en: 'End the chain here' },
  edit: { jp: '{直|なお}す', en: 'Edit' },
  playAnyway: { jp: 'それ でも {出|だ}す', en: 'Play anyway' },
  skip: { jp: '{飛|と}ばす', en: 'Skip' },
  rematch: { jp: 'もう {一局|いっきょく}', en: 'Rematch' },
  change: { jp: '{設定|せってい} を {変|か}える', en: 'Change setup' },
  look: { jp: '{振|ふ}り{返|かえ}る', en: 'Look back at the chain' },
  review: { jp: '{記録|きろく} を {見|み}る', en: 'Review a saved chain' },
  pin: { jp: '{残|のこ}す', en: 'Pin' },
  unpin: { jp: '{外|はず}す', en: 'Unpin' },
  primer: { jp: '{言葉|ことば} を {少|すこ}し {覚|おぼ}える', en: 'Learn a few more words together' },
  demo: { jp: '{見本|みほん} を {見|み}る', en: 'Show me how it goes' },
  skipDemo: { jp: '{見本|みほん} は いい', en: 'Skip demonstration' },
  keepLater: { jp: '{後|あと} で {続|つづ}ける', en: 'Keep it for later' },
  keepPlaying: { jp: '{続|つづ}ける', en: 'Keep playing' },
  restLater: { jp: '{休|やす}んで {後|あと} で {続|つづ}ける', en: 'Rest here and resume later' },
  talkReflect: { jp: '{話|はな}す ： どう {遊|あそ}んだ か', en: 'Talk: How we played' },
  reflectTitle: { jp: 'どう {遊|あそ}んだ か', en: 'How we played' },
  wordplay: { jp: 'しりとり の {記録|きろく}', en: 'Wordplay' },
  yourTurn: { jp: 'あなた の {番|ばん}', en: 'Your turn' },
  starter: { jp: '{最初|さいしょ} の {言葉|ことば}', en: 'Starter' },
  you: { jp: 'あなた', en: 'You' },
  used: { jp: '{使|つか}った', en: 'used' },
  endsN: { jp: 'ん で {終|お}わる', en: 'ends in ん' },
  stateNone: { jp: 'まだ', en: 'Not played' },
  statePlayed: { jp: '{遊|あそ}んだ', en: 'Played' },
  stateWon: { jp: '{勝|か}った', en: 'Won' },
  where: { jp: '{宿|やど} や {茶屋|ちゃや} で 、 {一緒|いっしょ} に {休|やす}む {時|とき}', en: 'At a rest stop with your companion: an inn, the teahouse, a hut or a camp' },
};
