// Converts cached KanjiVG SVGs into src/recog/10_strokedata.js.
//   node tools/kanjivg/fetch.mjs && node tools/kanjivg/convert.mjs
//
// For every character: the stroke paths are read in KanjiVG stroke-number order,
// each path is flattened (cubic/quadratic beziers sampled densely), resampled at
// ~0.5 unit spacing, simplified with Ramer–Douglas–Peucker (eps 0.45) and
// quantised to integers in KanjiVG's 109×109 box. Stroke order and direction
// are exactly KanjiVG's. Each point is packed into 3 base64url characters
// (value x*109+y); strokes are separated by a space.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ALL, KANA, KANJI, hex5, KANJIVG_COMMIT } from './chars.mjs';
import { flatten, resampleBySpacing, rdp } from './svgpath.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..', '..');
const CACHE = path.join(here, '.cache', 'kanjivg');
const OUT = path.join(root, 'src', 'recog', '10_strokedata.js');

export const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
export const BOX = 109;

export function encodeStroke(pts) {
  let s = '';
  for (const [x, y] of pts) {
    const v = x * BOX + y;
    s += B64[(v >> 12) & 63] + B64[(v >> 6) & 63] + B64[v & 63];
  }
  return s;
}
export function decodeStroke(s) {
  const out = [];
  for (let i = 0; i + 2 < s.length; i += 3) {
    const v = (B64.indexOf(s[i]) << 12) | (B64.indexOf(s[i + 1]) << 6) | B64.indexOf(s[i + 2]);
    out.push([Math.floor(v / BOX), v % BOX]);
  }
  return out;
}

export function readKanjiVG(svg, ch) {
  const h = hex5(ch);
  const strokes = [];
  for (const m of svg.matchAll(/<path\b[^>]*>/g)) {
    const tag = m[0];
    const id = /\bid="kvg:([0-9a-f]+)-s(\d+)"/.exec(tag);
    const d = /\sd="([^"]+)"/.exec(tag);
    if (!id || !d) continue;
    if (id[1] !== h) throw new Error(`${ch}: unexpected path id ${id[1]}`);
    strokes.push({ n: +id[2], d: d[1] });
  }
  strokes.sort((a, b) => a.n - b.n);
  strokes.forEach((s, i) => { if (s.n !== i + 1) throw new Error(`${ch}: stroke numbering gap at ${i + 1}`); });
  return strokes.map((s) => flatten(s.d));
}

export function compactStroke(dense) {
  const even = resampleBySpacing(dense, 0.5);
  const simp = rdp(even, 0.45);
  const q = [];
  for (const [x, y] of simp) {
    const p = [Math.min(BOX - 1, Math.max(0, Math.round(x))), Math.min(BOX - 1, Math.max(0, Math.round(y)))];
    const last = q[q.length - 1];
    if (!last || last[0] !== p[0] || last[1] !== p[1]) q.push(p);
  }
  if (q.length === 1) q.push(q[0].slice()); // a dot still has a start and an end
  return q;
}

function main() {
  const data = {};
  const missing = [];
  let points = 0, maxErr = 0;
  for (const ch of ALL) {
    const f = path.join(CACHE, `${hex5(ch)}.svg`);
    if (!fs.existsSync(f)) { missing.push(ch); continue; }
    const strokes = readKanjiVG(fs.readFileSync(f, 'utf8'), ch);
    const enc = strokes.map((dense) => {
      const q = compactStroke(dense);
      points += q.length;
      // Fidelity check: every dense sample must lie close to the stored polyline.
      for (const p of dense) {
        let best = Infinity;
        for (let i = 1; i < q.length; i++) best = Math.min(best, segDist(p, q[i - 1], q[i]));
        if (q.length < 2) best = Math.hypot(p[0] - q[0][0], p[1] - q[0][1]);
        maxErr = Math.max(maxErr, best);
      }
      const e = encodeStroke(q);
      const back = decodeStroke(e);
      if (JSON.stringify(back) !== JSON.stringify(q)) throw new Error(`${ch}: codec round-trip failed`);
      return e;
    });
    data[ch] = enc.join(' ');
  }
  const lines = [];
  lines.push('/* GENERATED by tools/kanjivg/convert.mjs — do not edit by hand.');
  lines.push(' *');
  lines.push(' * Stroke data derived from KanjiVG (https://kanjivg.tagaini.net,');
  lines.push(' * https://github.com/KanjiVG/kanjivg, commit ' + KANJIVG_COMMIT.slice(0, 12) + '),');
  lines.push(' * Copyright (C) 2009-2026 Ulrich Apel and the KanjiVG project, licensed under');
  lines.push(' * Creative Commons Attribution-Share Alike 3.0 (CC BY-SA 3.0,');
  lines.push(' * https://creativecommons.org/licenses/by-sa/3.0/). This file is an adapted');
  lines.push(' * form: paths were sampled into point sequences, simplified and quantised to');
  lines.push(' * integers in the 109x109 box. Stroke order and direction are unchanged.');
  lines.push(' * This adapted data is distributed under the same licence (CC BY-SA 3.0).');
  lines.push(' * See data/NOTICE.txt.');
  lines.push(' *');
  lines.push(' * Format: d[ch] = strokes separated by " "; each point is 3 base64url chars');
  lines.push(' * encoding x*109+y (integers, 0..108, SVG orientation: y grows downward). */');
  lines.push('var RB = (globalThis.RB = globalThis.RB || {});');
  lines.push('');
  lines.push('RB.recogData = {');
  lines.push("  source: 'KanjiVG " + KANJIVG_COMMIT.slice(0, 12) + " (CC BY-SA 3.0, Ulrich Apel)',");
  lines.push('  box: ' + BOX + ',');
  lines.push("  alphabet: '" + B64 + "',");
  lines.push('  d: {');
  for (const ch of ALL) if (data[ch] != null) lines.push(`    '${ch}': '${data[ch]}',`);
  lines.push('  },');
  lines.push('};');
  lines.push('');
  const js = lines.join('\n');
  fs.writeFileSync(OUT, js);
  const kana = KANA.filter((c) => data[c] != null).length;
  const kanji = [...KANJI].filter((c) => data[c] != null).length;
  console.log(`wrote ${path.relative(root, OUT)}: ${(Buffer.byteLength(js) / 1024).toFixed(1)} KiB, ${kana} kana + ${kanji} kanji, ${points} points, max polyline deviation ${maxErr.toFixed(2)} units`);
  if (missing.length) console.log('MISSING (not in cache / KanjiVG):', missing.join(' '));
}

function segDist(p, a, b) {
  const dx = b[0] - a[0], dy = b[1] - a[1];
  const L2 = dx * dx + dy * dy;
  let t = L2 ? ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / L2 : 0;
  t = Math.max(0, Math.min(1, t));
  return Math.hypot(p[0] - (a[0] + t * dx), p[1] - (a[1] + t * dy));
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
